schema = 3

[mod]
  [mod."github.com/coreos/go-systemd/v22"]
    version = "v22.5.0"
    hash = "sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
