schema = 3

[mod]
  [mod.'github.com/coreos/go-systemd/v22']
    version = 'v22.5.0'
    hash = 'sha256-E2zXikbmIQImghstLUWuey1YgA0Folu3F+fi5k4hCxA='

  [mod.'github.com/godbus/dbus/v5']
    version = 'v5.1.0'
    hash = 'sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY='

  [mod.'github.com/yuin/goldmark']
    version = 'v1.8.2'
    hash = 'sha256-LoWfW1Tb6mNuMR7SoA/4SJv4pTKfsVXqeXEVm4uEQ7Q='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
